services:
    thingsboard:
        image: thingsboard/tb-postgres
        ports:
            - 8080:8080
        environment:
            - HTTP_BIND_PORT=8080
            - SSL_ENABLED=true
            - SSL_PEM_CERT=/etc/certs/server.pem
            - SSL_PEM_KEY=/etc/certs/server_key.pem
        volumes:
             - ./tb-data:/data
             - ./certs:/etc/certs/

